[package]
name = "bigram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.12.1", features = ["train", "vision", "tch"] }
derive-new = "0.6.0"
rand = "0.8.5"
rayon = "1.9.0"